# Generated by Django 3.1.2 on 2020-12-02 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_page.departments')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_page.employees')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
