# Generated by Django 3.1.2 on 2020-12-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0002_auto_20201202_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
