# Generated by Django 3.1.2 on 2020-12-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='employee',
        ),
    ]
