# Generated by Django 3.1.2 on 2020-12-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0004_auto_20201204_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='departments',
            table='department',
        ),
    ]
