# Generated by Django 3.1.2 on 2020-12-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0005_auto_20201204_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptemp',
            name='dept_no',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='deptemp',
            name='emp_no',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='deptemp',
            table='emp_dept',
        ),
    ]
