# Generated by Django 3.1.2 on 2020-12-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0006_auto_20201204_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptmanager',
            name='dept_no',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='deptmanager',
            name='emp_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='deptmanager',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='deptmanager',
            table='manager_deptartment',
        ),
    ]
