# Generated by Django 3.1.2 on 2020-12-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0008_auto_20201204_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='emp_no',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='titles',
            table='title',
        ),
    ]
