# Generated by Django 3.1.2 on 2020-12-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0009_auto_20201204_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user_name',
        ),
    ]
