"""
Django settings for project_website project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
UTILS_DIR = os.path.join(BASE_DIR, "utils")

ACCOUNTANT_DIR = os.path.join(TEMPLATE_DIR, "accountant_temp")
EMPLOYEE_DIR = os.path.join(TEMPLATE_DIR, "employee_temp")
HOMEPAGE_DIR = os.path.join(TEMPLATE_DIR, "homepage_temp")
MANAGER_DIR = os.path.join(TEMPLATE_DIR, "manager_temp")

STATIC_DIR = os.path.join(BASE_DIR, "statics")

ALL_AUTH = os.path.join(TEMPLATE_DIR, "allauth")
ALL_AUTH_TEMPLATES = os.path.join(ALL_AUTH, "templates")
ACCOUNT_TEMPLATE = os.path.join(ALL_AUTH_TEMPLATES, "account")
OPENID_TEMPLATE = os.path.join(ALL_AUTH_TEMPLATES, "openid")
SOCIALACCOUNT_TEMPLATE = os.path.join(ALL_AUTH_TEMPLATES, "socialaccount")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@_iqzui&)%o@j)cf=f&v*hla#8j)$5zum+d41shw0#(=c%zfih'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['34.220.75.119']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'sslserver',

    'homepage',
    'accountant_page',
    'employee_page',

    'django_keycloak.apps.KeycloakAppConfig'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_keycloak.middleware.BaseKeycloakMiddleware',
]

ROOT_URLCONF = 'project_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ACCOUNTANT_DIR, EMPLOYEE_DIR, HOMEPAGE_DIR, MANAGER_DIR, ALL_AUTH, ALL_AUTH_TEMPLATES, 
                    ACCOUNT_TEMPLATE, OPENID_TEMPLATE, SOCIALACCOUNT_TEMPLATE, UTILS_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
KEYCLOAK_OIDC_PROFILE_MODEL = 'django_keycloak.OpenIdConnectProfile'

AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',
    'django_keycloak.auth.backends.KeycloakAuthorizationCodeBackend',

]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'



WSGI_APPLICATION = 'project_website.wsgi.application'

KEYCLOAK_OIDC_PROFILE_MODEL = 'django_keycloak.OpenIdConnectProfile'

auth_uri = "http://localhost:8080/auth/realms/testing"
client_id = "webapp"
public_uri = "http://127.0.0.1:8000/"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',

]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 9}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/statics/'
STATICFILES_DIRS = [
    STATIC_DIR
]

SITE_ID = 2
LOGIN_REDIRECT_URL = '/'



KEYCLOAK_OIDC_PROFILE_MODEL = 'django_keycloak.OpenIdConnectProfile'