# Generated by Django 3.1.2 on 2020-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField()),
                ('birthday_date', models.DateField()),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[(' ', 'Blank'), ('M', 'Male'), ('F', 'Female')], default=' ', max_length=1)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
