# Generated by Django 3.1.2 on 2020-11-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_number', models.IntegerField()),
                ('department_name', models.CharField(default='DEFAULT VALUE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField()),
                ('salary_amount', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.AddField(
            model_name='employees',
            name='department_number',
            field=models.IntegerField(default=121),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='job_title',
            field=models.CharField(default='DEFAULT VALUE', max_length=14),
        ),
        migrations.AddField(
            model_name='employees',
            name='manager_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=14),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[(' ', ' '), ('M', 'Male'), ('F', 'Female')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=16),
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
