# Generated by Django 3.1.2 on 2020-12-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20201202_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='user_name_profile',
        ),
    ]
