# Generated by Django 3.1.2 on 2020-12-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_page', '0003_delete_profile'),
        ('homepage', '0007_auto_20201202_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dept_no',
            field=models.ForeignKey(default=5465, on_delete=django.db.models.deletion.CASCADE, to='employee_page.departments'),
            preserve_default=False,
        ),
    ]
