# Generated by Django 3.1.2 on 2020-12-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_userprofile_dept_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dept_no',
        ),
    ]
