# Generated by Django 3.1.2 on 2020-12-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_userprofile_dept_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
